maintainer: syuilo <i@syuilo.com>
port: 616
https:
  enable: false
  key: null
  cert: null
webSecret: 'Himasaku#06160907'
mongodb:
  host: localhost
  port: 27017
  db: misskey
  user: syuilo
  pass: Syuilo8901
redis:
  host: localhost
  port: 6379
  pass: ''
elasticsearch:
  host: localhost
  port: 9200
  pass: ''
